___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
print("Версія NumPy:", np.__version__)
np.show_config()


Версія NumPy: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Progr

Створити вектор з 10 елементів, заповнений одиницями:

In [8]:
a = np.array([1]*10)
print('Вектор:\n', a)

Вектор:
 [1 1 1 1 1 1 1 1 1 1]


Створити вектор із значеннями від 0 до 10:

In [14]:
b = np.arange(0, 11, 1)
print('Вектор:\n', b)

Вектор:
 [ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [20]:
d = np.zeros((1,5,5), dtype='int32')
print(d)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [47]:
c_list = np.random.randint(0, 10, size=20)

for idx, x in np.ndenumerate(c_list):
    if x == 0:
        print('Індекс = ',idx)
print('----------------------------')
print(c_list)

Індекс =  (0,)
Індекс =  (1,)
Індекс =  (6,)
Індекс =  (10,)
Індекс =  (14,)
----------------------------
[0 0 5 9 9 9 0 3 4 5 0 2 3 5 0 8 4 6 4 9]


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [52]:
print(f'середнє значення = {np.mean(c_list)}')
print(f'середнє значення = {np.median(c_list)}')
print(f'середнє значення = {np.std(c_list)}')

середнє значення = 4.25
середнє значення = 4.0
середнє значення = 3.222964473896664


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [77]:
A = np.random.choice(25, size=(4, 2), replace=True)
B = np.random.choice(25, size=(2, 2), replace=True)
matrix = np.dot(A, B)
print(matrix, '\n')
print('----------------------------')
print(A, '\n')
print('----------------------------')
print(B, '\n')

[[363 467]
 [517 647]
 [705 991]
 [407 433]] 

----------------------------
[[ 8 13]
 [10 19]
 [22 23]
 [ 2 17]] 

----------------------------
[[ 8 21]
 [23 23]] 



Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [79]:
vector = matrix.flatten()
min_value = vector.min()
max_value = vector.max()
max_index = np.argmax(vector)
vector[max_index] = 0
print("Вектор після заміни:", vector)
print(f'Максимальне значення: {max_value}')
print(f'Мінімальне значення: {min_value}')

Вектор після заміни: [363 467 517 647 705   0 407 433]
Максимальне значення: 991
Мінімальне значення: 363


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [80]:
cor_matrix = np.corrcoef(matrix)

print("Кореляцію першого рядка матриці:")
print(cor_matrix)

Кореляцію першого рядка матриці:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Дано матрицю. Знайти ранг матриці:

In [81]:
a_matrix = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

rank = np.linalg.matrix_rank(a_matrix)
print("Ранг матриці:", rank)

Ранг матриці: 3


Знайти визначник матриці:

In [84]:
vz = np.linalg.det(a_matrix)

print("Визначник матриці:", vz)

Визначник матриці: 440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [85]:

# Знайти власні значення та власні вектори матриці
eigenvalues, eigenvectors = np.linalg.eig(a_matrix)

# Вивести власні значення
print("Власні значення:", eigenvalues)

# Вивести власні вектори
print("Власні вектори:", eigenvectors)

Власні значення: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори: [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [87]:
a = np.random.randint(0,10,50)

# Знайти кількість входжень кожного значення в масиві
counts = np.bincount(a)

# Знайти індекс значення з найбільшою кількістю входжень
most_frequent_value = np.argmax(counts)

# Вивести число з найбільшою кількістю входжень
print("Число, що найчастіше зустрічається:", most_frequent_value)
print('-----------------------------------------------------')
print(a)

Число, що найчастіше зустрічається: 5
-----------------------------------------------------
[9 0 7 1 7 2 7 6 4 0 9 1 2 5 8 6 5 5 2 5 8 0 7 8 6 8 5 5 3 5 4 1 5 9 5 9 3
 8 4 1 7 1 3 5 6 7 7 2 3 2]


Виведіть лише парні числа, що діляться на 5:

In [92]:
mas = np.random.randint(0,10,50)

for el in mas:
    if el%5 == 0:
        if el%2 == 0:
            print(el)

print(mas)

0
0
[4 3 6 4 8 3 8 9 8 7 1 5 0 1 5 1 8 1 0 4 9 1 6 5 6 7 8 1 5 6 4 6 6 2 9 1 6
 6 7 4 2 1 9 6 7 6 1 2 9 2]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [96]:
a = np.array([[2, 5], [1, -10]])
b = np.array([1, 3])
xy = np.linalg.solve(a, b)

print(xy)

[ 1.  -0.2]
